chore: rename validation job and add force push token check

diff --git a/.github/workflows/manual-release.yml b/.github/workflows/manual-release.yml
--- a/.github/workflows/manual-release.yml
+++ b/.github/workflows/manual-release.yml
@@ -21,8 +21,8 @@ permissions:
   contents: write
 
 jobs:
-  validate-branch:
-    name: Validate branch
+  validate-environment:
+    name: Validate workflow environment
     runs-on: ubuntu-latest
     timeout-minutes: 60
 
@@ -34,12 +34,19 @@ jobs:
             echo "::error title=Branch validation failed::This workflow can only be run on the main branch."
             exit 1
           fi
+      - name: Check for force push token
+        id: check-force-push-token
+        run: |
+          if [[ -z "${{ secrets.FORCE_PUSH_TOKEN }}" ]]; then
+            echo "::error title=Missing FORCE_PUSH_TOKEN::The FORCE_PUSH_TOKEN secret is not set. Please set it in the repository settings."
+            exit 1
+          fi
 
   force-bump-version:
     name: Force bump version
     runs-on: ubuntu-latest
     timeout-minutes: 10
-    needs: validate-branch
+    needs: validate-environment
     env:
       BUMP_MESSAGE: ${{ github.event.inputs.bump-message }}
 
@@ -47,7 +54,7 @@ jobs:
       - name: Clone repository
         uses: actions/checkout@v7
         with:
-          fetch-depth: "0"
+          token: ${{ secrets.FORCE_PUSH_TOKEN }}
       - name: Configure git
         run: |
           git config --global user.email "${{ github.actor }}@users.noreply.github.com"
